### ISSUE TITLE
Questions with "Replicate" Layers

### ISSUE THREAD

**Issue by songwoh** [snap-research/HyperHuman#4]
Thanks for sharing nice work.

I wanted to ask what "replicate layers" means. Does replicating include the model weights? Or, does it simply mean replicating same blocks (architecture), and each branch has their own set of weights?

It seems like Figure 2. is showing that each expert branches have their own set of weights for (first few and last few Downsample /Upsample blocks), and the intermediate blocks are shared between the experts. But it was not clear from the paper itself, and so I would like some explanation.

If my understanding is correct, then how are the features from different branches fused together? Is it simple addition of features before passing the "shared" intermediate layers?

Thank you.

**Comment by alvinliu0** [comment]
Hi, many thanks for your interest in our work!

The "replicate" means replicating the block architecture, while the parameters of each branch are not shared, just as illustrated in the Figure2. When fusing features from different branches, we tried average, sum, and learnable conv, and we find that first normalize each branch's latent distribution to similar mean and std with RGB branch, and then average them together yields the best result, pseudo-code like this:

output = avg(normalize(Enc(depth)), normalize(Enc(normal)), Enc(rgb))

Thank you so much for pointing out this unclearness, and we will clarify it in the revision:)

Best

**Comment by songwoh** [comment]
Thanks for the clarification!

**Comment by HiSultryMan** [comment]
> normal

one question for the detail, since feature out from the first down_block will be fused, will skip concat do seperately for each branch or simply do fused feature?

**Comment by alvinliu0** [comment]
Yeah, exactly. The skip connection will be done separately. 

For example, for the first RGB DownBlock, its output will be skip-connected to the last RGB UpBlock. And the same for depth and surface-normal branches. In this way, the features of different targets will not be mixed together. 

For the latter blocks where these three branches are already fused together, just skip-connected to the corresponding shared block. For example, the second DownBlock, which has already taken the fused RGB+depth+normal, skip-connect to the last second UpBlock, which also copes with the fused RGB+depth+normal features. The Figure2 gives a more vivid visualization for the skip connection design.

Best

**Comment by duyguceylan** [comment]
Thanks for your great work! When you do the normalization, do you the channel wise normalization based on the mean and std of each channel. In SD, a global scaling factor is used for RGB, do you replace this with channelwise mean and scaling factors for each modality?

**Comment by alvinliu0** [comment]
Hi, many thanks for your interest in our work!

The process of normalization is like this: we make thorough statistics on the latent representation mean and std of RGB, depth, surface-normal, and body skeleton, which is after the original DM VAE scaling factor. For example:

```python 
rgb_latents = vae.encode(images).latent_dist.sample()
rgb_latents = rgb_latents * vae.config.scaling_factor

depth_latents = vae.encode(images).latent_dist.sample()
depth_latents = depth_latents * vae.config.scaling_factor
```

After the flatten, we can calculate the mean and std of them like:

```python 
rgb_mean, rgb_std = np.mean(rgb_latents), np.std(rgb_latents)
depth_mean, depth_std = np.mean(depth_latents), np.std(depth_latents)
```

Finally, at the training stage, you simply need to do like this:

```python 
midas_depth_latents = vae.encode(batch["midas_depth"].to(weight_dtype)).latent_dist.sample()
midas_depth_latents = midas_depth_latents * vae.config.scaling_factor
if args.normalize_dist:
    midas_depth_latents = (midas_depth_latents - args.depth_mean) / args.depth_std * args.rgb_std + args.rgb_mean
```

Best

**Comment by ShunyuYao** [comment]
> Hi, many thanks for your interest in our work!
> 
> The "replicate" means replicating the block architecture, while the parameters of each branch are not shared, just as illustrated in the Figure2. When fusing features from different branches, we tried average, sum, and learnable conv, and we find that first normalize each branch's latent distribution to similar mean and std with RGB branch, and then average them together yields the best result, pseudo-code like this:
> 
> output = avg(normalize(Enc(depth)), normalize(Enc(normal)), Enc(rgb))
> 
> Thank you so much for pointing out this unclearness, and we will clarify it in the revision:)
> 
> Best

Could you please tell me how to normalize each branch's latent distribution in the feature fusion step, since the VAE latents are already normalized as you mentioned at the beginning. Thanks!
