### ISSUE TITLE
Question about depth map

### ISSUE THREAD

**Issue by Pang-Yatian** [snap-research/HyperHuman#5]
Hi, thanks for your great work.

I am confused about how the depth map is processed. If I understand correctly, the depth map has only one channel. Then how can it be encoded by the vae encoder? Could you please provide more details? Thank you.

**Comment by alvinliu0** [comment]
Hi, many thanks for your interest in our work!

We can just use PIL convert 'rgb' to change single-channel depth image to the three-channel RGB-like image. Besides, we have extensively verified the pretrained VAE's reconstruction ability on multiple structure maps, e.g., depth map, surface-normal map, body skeleton map. The recon quality is pretty good, so we can just convert them into three-channel RGB-image for encoding-decoding.

Best

**Comment by Pang-Yatian** [comment]
Thank you!
